name: KB STRIDE CI

on:
  push:
    branches:
      - feature/application-logging

  workflow_dispatch:

jobs:

  build:
    name: Maven Clean Install
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Clean Install
        run: mvn clean install
